-- Seed de iniciativas (dados de desenvolvimento; em produção: import AR)
-- Executado por: supabase db reset

insert into public.iniciativas (
  id, id_oficial, titulo, tipo, legislatura, numero, autores,
  data_entrada, data_votacao, estado, tema,
  descricao_oficial, explicacao, links, resultado_partidos
) values
(
  'pl-42-xvi',
  'PL 42/XVI/1',
  'Projeto de Lei que reforça a transparência das votações parlamentares',
  'Projeto de Lei',
  'XVI',
  42,
  array['Grupo Parlamentar do PS'],
  '2025-11-12',
  '2026-03-18',
  'aprovado',
  'Instituições',
  'Procede à alteração do Regimento da Assembleia da República, prevendo a publicação atempada e em formato aberto dos resultados nominais de todas as votações em plenário.',
  'A iniciativa propõe que os resultados de todas as votações em Plenário sejam publicados de forma atempada, em formatos reutilizáveis (JSON/CSV), incluindo o sentido de voto de cada deputado, quando a votação for nominal.',
  '[{"label":"Texto na AR","url":"https://www.parlamento.pt"}]'::jsonb,
  '{"ps":"favor","psd":"favor","chega":"abstencao","il":"favor","be":"favor","pcp":"favor","livre":"favor","pan":"favor","cds":"contra"}'::jsonb
),
(
  'pl-118-xvi',
  'PL 118/XVI/1',
  'Proposta de Lei do Orçamento do Estado para 2026',
  'Proposta de Lei',
  'XVI',
  118,
  array['Governo'],
  '2025-10-10',
  '2025-11-28',
  'aprovado',
  'Economia',
  'Aprova o Orçamento do Estado para o ano económico de 2026.',
  'Documento anual que define receitas e despesas públicas para 2026.',
  '[{"label":"Texto na AR","url":"https://www.parlamento.pt"}]'::jsonb,
  '{"ps":"favor","psd":"contra","chega":"contra","il":"contra","be":"contra","pcp":"contra","livre":"abstencao","pan":"abstencao","cds":"contra"}'::jsonb
),
(
  'pj-r-33-xvi',
  'PjR 33/XVI/1',
  'Projeto de Resolução sobre habitação acessível nas áreas metropolitanas',
  'Projeto de Resolução',
  'XVI',
  33,
  array['Grupo Parlamentar do BE', 'Grupo Parlamentar do LIVRE'],
  '2026-01-20',
  '2026-04-09',
  'rejeitado',
  'Habitação',
  'Recomenda ao Governo medidas urgentes de habitação a custos acessíveis nas Áreas Metropolitanas de Lisboa e do Porto.',
  'Resolução (não vinculativa como uma lei) que recomenda políticas de habitação.',
  '[{"label":"Texto na AR","url":"https://www.parlamento.pt"}]'::jsonb,
  '{"ps":"contra","psd":"contra","chega":"contra","il":"contra","be":"favor","pcp":"favor","livre":"favor","pan":"favor","cds":"contra"}'::jsonb
),
(
  'pl-7-xvi',
  'PL 7/XVI/1',
  'Projeto de Lei de proteção da costa e zonas húmidas',
  'Projeto de Lei',
  'XVI',
  7,
  array['Grupo Parlamentar do PAN', 'Grupo Parlamentar do LIVRE'],
  '2025-09-03',
  '2026-02-11',
  'aprovado',
  'Ambiente',
  'Estabelece medidas de proteção reforçada da orla costeira e de zonas húmidas de interesse nacional.',
  'Reforça regras de construção e uso do solo na orla costeira e em zonas húmidas classificadas.',
  '[{"label":"Texto na AR","url":"https://www.parlamento.pt"}]'::jsonb,
  '{"ps":"favor","psd":"abstencao","chega":"contra","il":"abstencao","be":"favor","pcp":"favor","livre":"favor","pan":"favor","cds":"contra"}'::jsonb
),
(
  'mocao-confianca-1',
  'Moção 1/XVI',
  'Moção de confiança ao Governo',
  'Moção',
  'XVI',
  1,
  array['Governo'],
  '2025-04-02',
  '2025-04-10',
  'aprovado',
  'Instituições',
  'Moção de confiança apresentada pelo Governo à Assembleia da República.',
  'Instrumento em que o Governo solicita a confiança da Assembleia da República.',
  '[{"label":"Texto na AR","url":"https://www.parlamento.pt"}]'::jsonb,
  '{"ps":"favor","psd":"contra","chega":"contra","il":"contra","be":"contra","pcp":"contra","livre":"abstencao","pan":"abstencao","cds":"contra"}'::jsonb
),
(
  'pl-201-xvi',
  'PL 201/XVI/1',
  'Projeto de Lei sobre literacia digital e cidadania nas escolas',
  'Projeto de Lei',
  'XVI',
  201,
  array['Grupo Parlamentar da IL', 'Grupo Parlamentar do PSD'],
  '2026-05-14',
  null,
  'em_discussao',
  'Educação',
  'Introduz conteúdos obrigatórios de literacia digital, pensamento crítico e cidadania no ensino básico e secundário.',
  'Ainda em discussão — os cidadãos podem votar; o resultado oficial da AR será actualizado quando existir votação.',
  '[{"label":"Texto na AR","url":"https://www.parlamento.pt"}]'::jsonb,
  '{"ps":"nao_participou","psd":"nao_participou","chega":"nao_participou","il":"nao_participou","be":"nao_participou","pcp":"nao_participou","livre":"nao_participou","pan":"nao_participou","cds":"nao_participou"}'::jsonb
),
(
  'pj-r-12-xvi',
  'PjR 12/XVI/1',
  'Projeto de Resolução — reforço do SNS no interior do país',
  'Projeto de Resolução',
  'XVI',
  12,
  array['Grupo Parlamentar do PCP'],
  '2025-12-02',
  '2026-01-22',
  'aprovado',
  'Saúde',
  'Recomenda ao Governo medidas de reforço da rede de cuidados de saúde no interior e regiões autónomas.',
  'Foca o acesso a cuidados em territórios de baixa densidade.',
  '[{"label":"Texto na AR","url":"https://www.parlamento.pt"}]'::jsonb,
  '{"ps":"favor","psd":"favor","chega":"abstencao","il":"abstencao","be":"favor","pcp":"favor","livre":"favor","pan":"favor","cds":"favor"}'::jsonb
),
(
  'pl-55-xvi',
  'PL 55/XVI/1',
  'Projeto de Lei de alteração ao Código do Trabalho — teletrabalho',
  'Projeto de Lei',
  'XVI',
  55,
  array['Grupo Parlamentar do PSD'],
  '2026-02-28',
  '2026-06-04',
  'rejeitado',
  'Trabalho',
  'Altera o regime de teletrabalho no Código do Trabalho.',
  'Propõe regras sobre elegibilidade, compensação de custos e direito à desconexão.',
  '[{"label":"Texto na AR","url":"https://www.parlamento.pt"}]'::jsonb,
  '{"ps":"contra","psd":"favor","chega":"favor","il":"favor","be":"contra","pcp":"contra","livre":"abstencao","pan":"abstencao","cds":"favor"}'::jsonb
);
